AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: HFV Vereine FastAPI on Lambda (Function URL)

Globals:
  Function:
    Runtime: python3.11
    Timeout: 60
    MemorySize: 512
    Architectures: [arm64]
    Tracing: Active
    Environment:
      Variables:
        CACHE_FILE: /tmp/vereine_cache.json

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.main.handler
      CodeUri: .
      FunctionName: hfv-vereine-api
      Policies:
        - AWSLambdaBasicExecutionRole

      AutoPublishAlias: live

      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 1

      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins: ['*']
          AllowHeaders: ['*']
          AllowMethods: ['GET']
        Qualifier: live

  LogsRetention:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ApiFunction}
      RetentionInDays: 14

Outputs:
  FunctionUrl:
    Value: !GetAtt ApiFunctionUrl.FunctionUrl
    Description: Public Function URL
