name: CI
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Lint (ruff)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Ruff Lint
        run: ruff check .
      - name: Ruff Format (check only)
        run: ruff format --check

  test:
    name: Tests & OpenAPI
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest -q
      - name: Export OpenAPI (openapi.json)
        run: PYTHONPATH=. python tools/export_openapi.py
      - name: Validate OpenAPI (Python validator)
        run: python -m openapi_spec_validator openapi.json
